# Generated by Django 4.0.5 on 2022-06-24 15:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('worked_total', models.TimeField(default=datetime.time(0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField(verbose_name='Attendance Hour')),
            ],
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of work shift')),
                ('tolerance_time', models.TimeField(blank=True, null=True, verbose_name='Tolerance time')),
                ('entry1', models.TimeField(verbose_name='Fisrt entry')),
                ('exit1', models.TimeField(verbose_name='First exit')),
                ('entry2', models.TimeField(verbose_name='Second entry')),
                ('exit2', models.TimeField(verbose_name='Second exit')),
                ('entry3', models.TimeField(blank=True, null=True, verbose_name='Optional entry')),
                ('exit3', models.TimeField(blank=True, null=True, verbose_name='Optional exit')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.workshift', verbose_name='Work Shift')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=1, max_length=2)),
                ('worked_total', models.IntegerField(default=0, verbose_name='Total worked month in seconds')),
                ('attendance_day', models.ManyToManyField(to='attendance.attendanceday', verbose_name='Attendance registered in day')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='attendance_hour',
            field=models.ManyToManyField(to='attendance.attendancehour', verbose_name='Hour registered'),
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='employee_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employeeshift', verbose_name='Employee shift'),
        ),
    ]
