# Generated by Django 4.1 on 2022-09-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendanceday_attendance_hour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancehour',
            options={'ordering': ('hour',)},
        ),
        migrations.AddField(
            model_name='workshift',
            name='working_days',
            field=models.CharField(choices=[(0, 'Mon - Tue - Wed - Thu - Fri'), (1, 'Mon - Tue - Wed - Thu - Fri - Sat')], default=0, max_length=1),
        ),
    ]
